---
displaymanagers:
    - plasmalogin

defaultDesktopEnvironment:
    executable: "/usr/bin/startplasma-wayland"
    desktopFile: "plasma"

basicSetup: false
sysconfigSetup: false

plasmalogin:
    configuration_file: "/etc/plasmalogin.conf"
