---
displaymanagers:
    - sddm

defaultDesktopEnvironment:
    executable: "/usr/bin/startplasma-wayland"
    desktopFile: "plasma"

basicSetup: false
sysconfigSetup: false

sddm:
    configuration_file: "/etc/sddm.conf"
