---
efi:
    mountPoint: "/boot"
    recommendedSize: 1GiB
    minimumSize: 300MiB
    label: "EFI"

userSwapChoices:
    - none

luksGeneration: luks1
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultPartitionTableType: gpt
requiredPartitionTableType: gpt
defaultFileSystemType: "btrfs"
availableFileSystemTypes: [ "btrfs" ]
essentialMounts: [ "live-*", "control", "ventoy" ]

lvm:
    enable: false

enableLuksAutomatedPartitioning: false

partitionLayout:
    - name: "rootfs"
      filesystem: "btrfs"
      mountPoint: "/"
      size: 100%
      minSize: 16GiB

requiredStorage: 16
