---
dontChroot: true
timeout: 900
verbose: true

script:
    - command: "/usr/local/bin/simplearch-apply-gpu-driver ${ROOT} ${gs[packagechooser_gpu]}"
      timeout: 900

i18n:
    name: "Configuring video driver"
    name[pt_BR]: "Configurando driver de video"
