---
dontChroot: true
timeout: 60
verbose: true

script:
    - command: "/usr/local/bin/simplearch-preflight"
      timeout: 60

i18n:
    name: "Checking boot mode"
    name[pt_BR]: "Verificando modo de boot"
