---
dontChroot: true
timeout: 1200
verbose: true

script:
    - command: "/usr/local/bin/simplearch-postinstall ${ROOT} ${USER}"
      timeout: 1200

i18n:
    name: "Applying Simple Arch defaults"
    name[pt_BR]: "Aplicando padroes do Simple Arch"
