---
unpack:
    - source: "/run/archiso/bootmnt/simplearch/x86_64/airootfs.sfs"
      sourcefs: "squashfs"
      destination: ""
      exclude:
          - "/etc/calamares"
          - "/etc/polkit-1/rules.d/49-simplearch-calamares.rules"
          - "/etc/plasmalogin.conf"
          - "/etc/sudoers.d/10-simplearch"
          - "/etc/sysusers.d/simplearch.conf"
          - "/etc/tmpfiles.d/simplearch.conf"
          - "/home/simplearch"
          - "/opt/simplearch/offline-repo"
          - "/root/.automated_script.sh"
          - "/usr/local/bin/simplearch-apply-gpu-driver"
          - "/usr/local/bin/simplearch-postinstall"
          - "/usr/share/applications/simplearch-install.desktop"
      weight: 1
