---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
    requiredStorage: 5.5
    requiredRam: 1.0
    internetCheckUrl:
        - https://archlinux.org
        - https://kde.org
    check:
        - storage
        - ram
        - internet
        - screen
    required:
        - ram

geoip:
    style: "json"
    url: "https://geoip.kde.org/v1/calamares"
    selector: "country_code"
