d /home/simplearch 0755 simplearch simplearch -
d /home/simplearch/.config 0755 simplearch simplearch -
d /home/simplearch/Desktop 0755 simplearch simplearch -
C /home/simplearch/.zshrc 0644 simplearch simplearch - /etc/skel/.zshrc
C /home/simplearch/.config/kded6rc 0644 simplearch simplearch - /etc/skel/.config/kded6rc
C /home/simplearch/.config/plasma-localerc 0644 simplearch simplearch - /etc/skel/.config/plasma-localerc
C /home/simplearch/.config/plasma-welcomerc 0644 simplearch simplearch - /etc/skel/.config/plasma-welcomerc
C /home/simplearch/.config/kdeglobals 0644 simplearch simplearch - /etc/skel/.config/kdeglobals
C /home/simplearch/Desktop/simplearch-install.desktop 0755 simplearch simplearch - /etc/skel/Desktop/simplearch-install.desktop
